version: "3.8"
services:
  front:
    image: sermalenk/skypro-front:lesson-35
    depends_on:
      - api
    ports:
      - '80:80'

  api:
    build:
      context: .
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      migrations:
        condition: service_completed_successfully

  migrations:
    build:
      context: .
    env_file:
      - .env
    command: >
      sh -c 'poetry run python3 manage.py makemigrations && poetry run python3 manage.py migrate'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
