# Generated by Django 4.1.7 on 2023-04-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_tguser_verification_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tguser",
            old_name="telegram_chat_id",
            new_name="tg_id",
        ),
        migrations.RemoveField(
            model_name="tguser",
            name="telegram_user_ud",
        ),
        migrations.AddField(
            model_name="tguser",
            name="username",
            field=models.CharField(
                default="empty", max_length=50, verbose_name="Telegram user"
            ),
            preserve_default=False,
        ),
    ]
