# Generated by Django 4.1.7 on 2023-04-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0005_alter_tguser_bot_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tguser",
            name="bot_state",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Added"),
                    (2, "Confirmed"),
                    (3, "Wait Category"),
                    (4, "Wait Title"),
                ],
                default=1,
                verbose_name="Bot State",
            ),
        ),
    ]
