# Generated by Django 4.1.7 on 2023-04-17 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(blank=True, null=True, verbose_name="Create date"),
                ),
                (
                    "updated",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last updated"
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Is deleted"
                    ),
                ),
            ],
            options={
                "verbose_name": "Board",
                "verbose_name_plural": "Boards",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="board",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="goals.board",
                verbose_name="Board",
            ),
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(blank=True, null=True, verbose_name="Create date"),
                ),
                (
                    "updated",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last updated"
                    ),
                ),
                (
                    "role",
                    models.SmallIntegerField(
                        choices=[(1, "Owner"), (2, "Reader"), (3, "Writer")],
                        default=1,
                        verbose_name="Role",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participants",
                        to="goals.board",
                        verbose_name="Board",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
                "unique_together": {("board", "user")},
            },
        ),
    ]
