# Generated by Django 4.1.7 on 2023-04-17 15:45

from django.db import migrations, transaction
from django.utils import timezone


def create_objects(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Category = apps.get_model('goals', 'Category')
    Board = apps.get_model('goals', 'Board')
    Participant = apps.get_model('goals', 'Participant')

    with transaction.atomic():
        for user in User.objects.all():
            new_board = Board.objects.create(
                title='My purposes',
                created=timezone.now().date(),
                updated=timezone.now().date(),
                is_deleted=False,
            )

            Participant.objects.create(
                board=new_board,
                user=user,
                role=1,
                created=timezone.now().date(),
                updated=timezone.now().date(),
            )

            Category.objects.filter(
                user=user,
            ).update(board=new_board)


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0002_board_category_board_participant"),
    ]

    operations = [
        migrations.RunPython(create_objects)
    ]
